const industry: { [key: string]: string[] } = {
  Agriculture: [
    'Agronomy',
    'Horticulture',
    'Sustainable Farming',
    'Pesticide Application',
    'Livestock Management',
    'Crop Rotation',
    'Organic Farming',
    'Soil Science',
    'Precision Agriculture',
    'Farm Equipment Operation',
    'Agricultural Economics',
    'Water Resources Management',
    'Plant Pathology',
    'Agribusiness Management',
    'Food Safety',
    'Agricultural Policy',
    'Entomology',
    'Irrigation Systems',
    'Greenhouse Management',
    'Animal Husbandry',
    'Agricultural Research',
    'Seed Technology',
    'Fertilizer Management',
    'Agricultural Extension',
    'Rural Development',
    'Farm Management Software',
    'GIS and Remote Sensing',
    'Aquaculture',
    'Commodity Marketing',
    'Forestry',
  ],
  Automobiles: [
    'Automotive Engineering',
    'Vehicle Design',
    'CAD Software',
    'Automotive Systems',
    'Manufacturing Processes',
    'Quality Assurance',
    'Project Management',
    'Lean Manufacturing',
    'Powertrain Systems',
    'Chassis Engineering',
    'Suspension Design',
    'Brake Systems',
    'Automotive Electronics',
    'Diagnostics',
    'Supplier Management',
    'Emission Control',
    'Product Development',
    'Aerodynamics',
    'Thermal Management',
    'Material Science',
    '3D Modeling',
    'Automotive Safety',
    'Hybrid Technology',
    'Battery Management Systems',
    'Automotive Standards',
    'Customer Service',
    'Sales and Marketing',
    'Warranty Administration',
    'Aftermarket Support',
    'Automotive Apprenticeship',
  ],
  Aviation: [
    'Pilot',
    'Flight Operations',
    'Aviation Maintenance',
    'Aerospace Engineering',
    'Air Traffic Control',
    'Flight Safety',
    'Aircraft Navigation',
    'Federal Aviation Regulations',
    'Crew Resource Management',
    'Avionics',
    'Civil Aviation Authority',
    'Flight Planning',
    'Commercial Aviation',
    'Flight Instructor',
    'Type Rating',
    'Ground Instruction',
    'Flight Simulation',
    'Aircraft Systems',
    'Airworthiness',
    'Airport Management',
    'First Officer',
    'Cabin Crew',
    'Flight Dispatcher',
    'Airline Management',
    'Aviation Security',
    'Airfield Operations',
    'Aviation Electronics',
    'Aircraft Maintenance Technician',
    'Flight Attendant',
    'Jet Engine Mechanics',
  ],
  Banking: [
    'Financial Analysis',
    'Risk Management',
    'Portfolio Management',
    'Investment Strategies',
    'Loan Processing',
    'Credit Analysis',
    'Regulatory Compliance',
    'Anti-Money Laundering',
    'Know Your Customer',
    'Financial Modeling',
    'Asset Management',
    'Commercial Banking',
    'Retail Banking',
    'Sales Management',
    'Relationship Management',
    'Underwriting',
    'Treasury Management',
    'Financial Planning',
    'Customer Service',
    'Cash Handling',
    'Payment Processing',
    'Banking Operations',
    'Financial Services',
    'Financial Reporting',
    'Branch Management',
    'Wealth Management',
    'Securities Trading',
    'Interest Rate Analysis',
    'Corporate Finance',
    'Financial Product Sales',
  ],
  Biotechnology: [
    'Molecular Biology',
    'Bioprocessing',
    'CRISPR',
    'Genomics',
    'Proteomics',
    'Cell Culture',
    'Bioinformatics',
    'PCR',
    'DNA Sequencing',
    'Microbiology',
    'Flow Cytometry',
    'Immunology',
    'ELISA',
    'Biochemistry',
    'Tissue Engineering',
    'Fermentation',
    'HPLC',
    'Western Blot',
    'GLP',
    'GMP',
    'Regulatory Affairs',
    'Bioreactor',
    'Drug Development',
    'Vaccine Development',
    'Quality Control',
    'Assay Development',
    'Mass Spectrometry',
    'Enzyme Kinetics',
    'Stem Cells',
    'Biosensors',
  ],
  Chemicals: [
    'Chemical Engineering',
    'Process Optimization',
    'Petrochemicals',
    'Laboratory Techniques',
    'Safety Procedures',
    'Quality Control',
    'Organic Chemistry',
    'Inorganic Chemistry',
    'Polymer Science',
    'Analytical Instruments',
    'Hazard Analysis',
    'Chemical Reactions',
    'Batch Processing',
    'Chemical Synthesis',
    'Pilot Plant',
    'HPLC',
    'GC-MS',
    'Spectroscopy',
    'Materials Science',
    'Catalysis',
    'Scale-up',
    'Compliance',
    'Regulatory Affairs',
    'Environmental Impact',
    'Process Control',
    'Chemical Plant Management',
    'Distillation',
    'Extraction',
    'Chemometrics',
    'Technical Reporting',
  ],
  Coal: [
    'Mining',
    'Underground Mining',
    'Surface Mining',
    'Coal Processing',
    'Mining Safety',
    'Mining Engineering',
    'Drilling',
    'Blasting',
    'Ventilation',
    'Mineral Exploration',
    'Coal Handling',
    'Mine Planning',
    'Geotechnical Engineering',
    'Reclamation',
    'Mine Supervisor',
    'Extraction Techniques',
    'Power Generation',
    'Heavy Equipment',
    'Project Management',
    'Resource Management',
    'Environmental Compliance',
    'Occupational Health',
    'Safety Management',
    'Surveying',
    'Mineral Processing',
    'Material Handling',
    'Energy Production',
    'Coal Preparation',
    'Fleet Management',
    'Operational Efficiency',
  ],
  Construction: [
    'Blueprint Reading',
    'Project Management',
    'OSHA Compliance',
    'Building Codes',
    'Safety Management',
    'Contract Negotiation',
    'Construction Planning',
    'Cost Estimation',
    'Quality Control',
    'Scheduling',
    'Site Supervision',
    'Material Procurement',
    'Risk Management',
    'AutoCAD',
    'BIM',
    'LEED Certification',
    'Concrete Forming',
    'Frame Carpentry',
    'Heavy Equipment Operation',
    'Subcontractor Management',
    'Change Orders',
    'Value Engineering',
    'Civil Engineering',
    'Structural Engineering',
    'Mechanical, Electrical, and Plumbing (MEP)',
    'Excavation',
    'Masonry',
    'Construction Software',
    'Building Inspections',
    'Welding',
  ],
  Defence: [
    'Security Clearance',
    'Military Operations',
    'National Security',
    'Intelligence Analysis',
    'Armed Forces',
    'Tactical Planning',
    'Combat Training',
    'Weapon Systems',
    'Surveillance',
    'Counterterrorism',
    'Risk Assessment',
    'Strategic Planning',
    'Cybersecurity',
    'Defence Procurement',
    'Operational Security',
    'Aerospace Engineering',
    'Military Experience',
    'Command and Control',
    'Military Leadership',
    'Defense Contracting',
    'Top Secret',
    'Force Protection',
    'Military Training',
    'Reconnaissance',
    'Defense Technology',
    'Project Management',
    'Crisis Management',
    'Electronic Warfare',
    'Mission Planning',
    'Naval Operations',
  ],
  'E-commerce': [
    'E-commerce Management',
    'Online Sales Strategies',
    'Digital Marketing',
    'Customer Relationship Management (CRM)',
    'Search Engine Optimization (SEO)',
    'Pay-Per-Click (PPC) Advertising',
    'Social Media Marketing',
    'E-commerce Platform Development',
    'Product Management',
    'Web Analytics',
    'Conversion Rate Optimization',
    'Email Marketing',
    'Inventory Management',
    'Supply Chain Coordination',
    'Market Research',
    'Content Management Systems (CMS)',
    'User Experience (UX) Design',
    'Data Analysis',
    'Mobile Commerce',
    'Customer Service',
    'Order Fulfillment',
    'Payment Gateway Integration',
    'Project Management',
    'Affiliate Marketing',
    'Brand Management',
    'Logistics Management',
    'Revenue Growth',
    'Merchant Services',
    'SSL Certificates',
    'Shopping Cart Software',
  ],
  'Education and Training': [
    'Curriculum Development',
    'Classroom Management',
    'Educational Technology',
    'Instructional Design',
    'Student Assessments',
    'Lesson Planning',
    'Educational Leadership',
    'Special Education',
    'Teaching',
    'Lecturing',
    'Academic Advising',
    'E-Learning',
    'Course Development',
    'Teacher Training',
    'Professional Development',
    'Student Engagement',
    'Faculty Development',
    'Online Education',
    'Pedagogy',
    'Student Counseling',
    'Learning Management Systems',
    'Education Administration',
    'Tutoring',
    'Research',
    'Student Achievement',
    'Accreditation',
    'Literacy',
    'Differentiated Instruction',
    'Education Policy',
    'Education Program Management',
  ],
  Electronics: [
    'Circuit Design',
    'PCB Layout',
    'Soldering',
    'Oscilloscope',
    'Multimeter',
    'Signal Processing',
    'Embedded Systems',
    'Microcontrollers',
    'VHDL',
    'ASIC',
    'Field-Programmable Gate Array (FPGA)',
    'Analog Circuit',
    'Digital Electronics',
    'Power Electronics',
    'Semiconductors',
    'Electrical Measurements',
    'Electromagnetic Compatibility (EMC)',
    'Radio-Frequency (RF) Engineering',
    'Instrumentation',
    'Schematics',
    'Wireless Communications',
    'Troubleshooting',
    'Automation',
    'MATLAB',
    'Simulink',
    'SPICE',
    'CAD Tools',
    'Test Equipment',
    'Quality Assurance (QA)',
    'Project Management',
  ],
  Energy: [
    'Renewable Energy',
    'Oil and Gas',
    'Project Management',
    'Sustainability',
    'Energy Efficiency',
    'Power Generation',
    'Solar Energy',
    'Wind Energy',
    'Energy Storage',
    'Environmental Compliance',
    'Petroleum Engineering',
    'Energy Markets',
    'Drilling',
    'Geothermal',
    'Electrical Engineering',
    'Pipeline Management',
    'Carbon Footprint Reduction',
    'Energy Policy',
    'Energy Trading',
    'Commodity Markets',
    'Utilities Management',
    'SCADA Systems',
    'Hydropower',
    'Nuclear Energy',
    'Thermodynamics',
    'Grid Management',
    'Energy Audit',
    'Regulatory Affairs',
    'Energy Conservation',
    'Alternative Energy',
  ],
  'Fast Moving Consumer Goods (FMCG)': [
    'Brand Management',
    'Market Research',
    'Sales Forecasting',
    'Product Development',
    'Supply Chain Management',
    'Inventory Management',
    'Trade Marketing',
    'Consumer Insights',
    'Retail Management',
    'Category Management',
    'Distribution Channel',
    'P&L Management',
    'Merchandising',
    'Cost Reduction',
    'Revenue Growth',
    'Strategic Planning',
    'Customer Relationship Management',
    'Negotiation Skills',
    'Competitive Analysis',
    'Point of Sale',
    'Key Account Management',
    'Marketing Strategy',
    'Business Development',
    'Logistics Coordination',
    'Operational Excellence',
    'Market Penetration',
    'SKU Management',
    'Promotional Campaigns',
    'Data Analysis',
    'Team Leadership',
  ],
  'Food Processing': [
    'HACCP',
    'GMP',
    'Food Safety',
    'Sanitation',
    'Quality Control',
    'FDA Regulations',
    'USDA Regulations',
    'Packaging',
    'Food Technology',
    'Product Development',
    'Continuous Improvement',
    'Supply Chain Management',
    'Food Microbiology',
    'Thermal Processing',
    'Food Chemistry',
    'Process Optimization',
    'Shelf Life Studies',
    'Ingredient Functionality',
    'Sensory Evaluation',
    'Batch Processing',
    'Food Preservation',
    'Food Engineering',
    'Good Manufacturing Practices',
    'Pasteurization',
    'Food Labeling',
    'Cross-Contamination',
    'Fermentation',
    'Nutritional Analysis',
    'Production Planning',
    'Food Manufacturing',
  ],
  Healthcare: [
    'Clinical Experience',
    'Patient Care',
    'Healthcare Management',
    'Electronic Medical Records (EMR)',
    'Medical Terminology',
    'HIPAA Compliance',
    'Nursing',
    'Healthcare Administration',
    'EHR (Electronic Health Records)',
    'CPR Certified',
    'Treatment Planning',
    'Medical Billing',
    'Phlebotomy Skills',
    'Case Management',
    'Infection Control',
    'Diagnostic Testing',
    'Surgery Assistance',
    'Patient Education',
    'Regulatory Compliance',
    'Medical Coding',
    'Public Health',
    'Healthcare Information Technology',
    'Pharmaceutical Knowledge',
    'Patient Advocacy',
    'Health Insurance',
    'Emergency Medicine',
    'Clinical Research',
    'Medical Devices',
    'Cardiopulmonary Resuscitation',
    'Disease Management',
  ],
  'Information Technology (IT)': [
    'Programming',
    'Cybersecurity',
    'Cloud Computing',
    'Data Analysis',
    'Machine Learning',
    'Artificial Intelligence',
    'Networking',
    'Software Development',
    'Database Management',
    'System Administration',
    'Technical Support',
    'Project Management',
    'DevOps',
    'ITIL',
    'Troubleshooting',
    'Information Security',
    'Scripting',
    'Web Development',
    'Agile Methodology',
    'Big Data',
    'User Experience',
    'Quality Assurance',
    'Business Intelligence',
    'Virtualization',
    'API Integration',
    'IT Compliance',
    'Scrum',
    'IT Strategy',
    'Version Control',
    'IT Infrastructure',
  ],
  Infrastructure: [
    'Civil Engineering',
    'Project Management',
    'Urban Planning',
    'Construction Management',
    'Structural Engineering',
    'Environmental Engineering',
    'Infrastructure Development',
    'Transportation Engineering',
    'Public Works',
    'Surveying',
    'Geotechnical Engineering',
    'Water Resources',
    'Sustainability',
    'Roadway Design',
    'AutoCAD',
    'BIM (Building Information Modeling)',
    'SCADA Systems',
    'Land Development',
    'Stormwater Management',
    'Site Planning',
    'Feasibility Studies',
    'Compliance Regulations',
    'GIS (Geographic Information Systems)',
    'Asset Management',
    'Contract Negotiation',
    'Project Estimation',
    'Quality Assurance',
    'Construction Supervision',
    'Value Engineering',
    'Risk Management',
  ],
  Insurance: [
    'Underwriting',
    'Risk Assessment',
    'Claims Adjusting',
    'Reinsurance',
    'Policy Administration',
    'Actuarial Analysis',
    'Customer Service',
    'Sales',
    'Product Development',
    'Insurance Regulations',
    'Loss Control',
    'Premium Auditing',
    'Casualty Insurance',
    'Life Insurance',
    'Health Insurance',
    'Property Insurance',
    'Insurance Broker',
    'Coverage Analysis',
    'Insurance Marketing',
    'Compliance',
    'Claims Processing',
    'Data Analysis',
    'Business Development',
    'Financial Planning',
    'Risk Management',
    'Insurance Software',
    'Agency Management',
    'Customer Relationship Management (CRM)',
    'Insurance Claims',
    'Policy Renewals',
  ],
  Manufacturing: [
    'Lean Manufacturing',
    'Six Sigma',
    'Continuous Improvement',
    'Process Optimization',
    'Production Planning',
    'Supply Chain Management',
    'Quality Control',
    'Kaizen',
    '5S Methodology',
    'Inventory Management',
    'Operations Management',
    'CNC Machining',
    'Welding',
    'Equipment Maintenance',
    'Safety Compliance',
    'ISO Certifications',
    'ERP Systems',
    'CAD/CAM',
    'Material Requirement Planning (MRP)',
    'Manufacturing Engineering',
    'Industrial Automation',
    'Root Cause Analysis',
    'Statistical Process Control (SPC)',
    'Just-In-Time (JIT) Production',
    'Total Quality Management (TQM)',
    'Machine Operation',
    'Product Development',
    'Assembly Line Management',
    'Preventive Maintenance',
    'Cost Reduction Strategies',
  ],
  'Media and Entertainment': [
    'Content Creation',
    'Digital Media',
    'Broadcasting',
    'Video Production',
    'Audio Engineering',
    'Screenwriting',
    'Multimedia Editing',
    'Visual Effects',
    'Animation',
    'Graphic Design',
    'Journalism',
    'Social Media Management',
    'Public Relations',
    'Advertising',
    'Branding',
    'Media Planning',
    'Storytelling',
    'Photography',
    'Podcasting',
    'Live Streaming',
    'Post-Production',
    'Camera Operation',
    'Sound Design',
    'Set Design',
    'Music Production',
    'Directing',
    'Script Supervision',
    'Casting',
    'Film Editing',
    'Media Strategy',
  ],
  Mining: [
    'Geology',
    'Mineral Exploration',
    'Drilling',
    'Blasting',
    'Safety Compliance',
    'Mine Planning',
    'Surveying',
    'Metallurgy',
    'Mining Engineering',
    'Environmental Management',
    'Excavation',
    'Underground Mining',
    'Open Pit Mining',
    'Resource Modeling',
    'Mine Ventilation',
    'Mine Rehabilitation',
    'Heavy Equipment Operation',
    'Rock Mechanics',
    'Project Management',
    'Process Optimization',
    'Feasibility Studies',
    'Material Handling',
    'QA/QC',
    'Hydrogeology',
    'GIS Mapping',
    'Mineral Processing',
    'Tailings Management',
    'Risk Assessment',
    'Mining Legislation',
    'Cost Control',
  ],
  'Oil and Gas': ['Oil', 'Gas'],
  Pharmaceuticals: [
    'Clinical Trials',
    'Pharmacovigilance',
    'Good Manufacturing Practice (GMP)',
    'Drug Development',
    'Regulatory Affairs',
    'Biotechnology',
    'Formulation',
    'Quality Control',
    'FDA Compliance',
    'Product Launch',
    'Research & Development (R&D)',
    'Biochemistry',
    'Molecular Biology',
    'Chemistry',
    'Toxicology',
    'Patent Filing',
    'SOPs',
    'Therapeutic Areas',
    'Validation',
    'Market Access',
    'Good Clinical Practice (GCP)',
    'Pharmaceutical Sales',
    'HPLC (High Performance Liquid Chromatography)',
    'Clinical Study Design',
    'Medical Affairs',
    'API (Active Pharmaceutical Ingredient)',
    'Laboratory Skills',
    'Compliance',
    'Data Analysis',
    'Patient Recruitment',
  ],
  'Real Estate': [
    'Property Management',
    'Real Estate Development',
    'Leasing Negotiations',
    'Market Analysis',
    'Investment Strategies',
    'Portfolio Management',
    'Real Estate Finance',
    'Commercial Real Estate',
    'Residential Sales',
    'Asset Management',
    'Tenant Relations',
    'Real Estate Transactions',
    'Due Diligence',
    'Property Marketing',
    'Lease Administration',
    'Real Estate Economics',
    'Urban Planning',
    'Sustainability',
    'Real Estate Law',
    'Construction Management',
    'Facility Management',
    'Appraisal',
    'Land Acquisition',
    'Brokerage',
    'Customer Service',
    'Renovation',
    'Real Estate License',
    'Escrow Management',
    'Zoning Compliance',
    'Risk Management',
  ],
  Retail: [
    'Customer Service',
    'Sales Targets',
    'Merchandising',
    'Inventory Management',
    'Visual Merchandising',
    'Point of Sale (POS) Systems',
    'Retail Sales',
    'Store Operations',
    'Loss Prevention',
    'Stock Control',
    'Product Knowledge',
    'Cash Handling',
    'Retail Marketing',
    'Sales Promotion',
    'Team Leadership',
    'Customer Satisfaction',
    'Store Management',
    'Employee Training',
    'Performance Management',
    'Budget Management',
    'Buying',
    'Retail Analytics',
    'Supply Chain Management',
    'Retail Strategy',
    'Brand Management',
    'Foot Traffic Analysis',
    'E-Commerce',
    'Store Layout',
    'Customer Loyalty Programs',
    'Trend Forecasting',
  ],
  Services: [
    'Customer Service',
    'Client Satisfaction',
    'Support',
    'Service Delivery',
    'Problem Solving',
    'Help Desk',
    'Service Level Agreement',
    'Call Center',
    'Troubleshooting',
    'Incident Management',
    'Technical Support',
    'Customer Relationship Management',
    'Account Management',
    'Service Operations',
    'Service Improvement',
    'Client Onboarding',
    'Complaint Handling',
    'Service Strategy',
    'Team Leadership',
    'Training and Development',
    'Project Coordination',
    'Retention Strategies',
    'Quality Assurance',
    'Feedback Collection',
    'Upselling',
    'Cross-selling',
    'Customer Experience',
    'B2B Services',
    'B2C Services',
    'Service Innovation',
  ],
  Steel: [
    'Metallurgy',
    'Continuous Casting',
    'Rolling Mill',
    'Blast Furnace',
    'Quality Control',
    'Heat Treatment',
    'Steel Fabrication',
    'Welding',
    'Corrosion Resistance',
    'Material Science',
    'Carbon Steel',
    'Alloy Development',
    'Strength Testing',
    'Process Optimization',
    'Plant Operations',
    'Steel Production',
    'Maintenance Engineering',
    'Project Management',
    'Supply Chain Management',
    'Environmental Compliance',
    'Safety Procedures',
    'Lean Manufacturing',
    'Cost Reduction Strategies',
    'ISO Standards',
    'Product Development',
    'Automated Systems',
    'Inventory Management',
    'Technical Specifications',
    'Operational Excellence',
    'Energy Efficiency',
  ],
  Telecommunications: [
    '5G',
    '4G LTE',
    'VoIP',
    'SIP',
    'Network Optimization',
    'Telecom Engineering',
    'Fiber Optics',
    'Wireless Communications',
    'Broadband',
    'RF Engineering',
    'Cellular Networks',
    'Microwave Transmission',
    'Satellite Communications',
    'Data Transmission',
    'Spectrum Management',
    'Telecom Regulations',
    'Network Security',
    'Project Management',
    'Telecommunications Infrastructure',
    'Customer Premises Equipment (CPE)',
    'Signal Processing',
    'Mobile Devices',
    'SDN (Software-Defined Networking)',
    'Troubleshooting',
    'Vendor Management',
    'Systems Integration',
    'Internet Protocols (IP)',
    'Quality of Service (QoS)',
    'Telecom Billing Systems',
    'NOC (Network Operations Center)',
  ],
  Textiles: [
    'Textile Design',
    'Pattern Making',
    'Fashion Design',
    'Weaving',
    'Knitting',
    'Dyeing',
    'Printing',
    'Fabric Technology',
    'Quality Control',
    'Garment Construction',
    'Merchandising',
    'Apparel Production',
    'Fashion Illustration',
    'Sourcing',
    'Supply Chain Management',
    'Product Development',
    'CAD Software',
    'Color Theory',
    'Material Science',
    'Costing',
    'Trend Analysis',
    'Technical Textiles',
    'Sustainability',
    'Compliance',
    'Textile Engineering',
    'Fashion Marketing',
    'Brand Management',
    'Fashion Shows',
    'Retail Management',
    'Customer Service',
  ],
  'Tourism and Hospitality': [
    'Hospitality Management',
    'Tourism Operations',
    'Customer Service',
    'Event Planning',
    'Front Office',
    'Hotel Management',
    'Tour Guiding',
    'Travel Coordination',
    'Reservation Systems',
    'Guest Relations',
    'Concierge Services',
    'Catering Management',
    'Food and Beverage',
    'Housekeeping',
    'Tour Package Development',
    'Language Proficiency',
    'Revenue Management',
    'Property Management Systems',
    'Sustainable Tourism',
    'Hospitality Marketing',
    'Destination Marketing',
    'Hospitality Sales',
    'Adventure Tourism',
    'Tourism Promotion',
    'Leisure Services',
    'Hospitality Law',
    'Hospitality Education',
    'Cultural Awareness',
    'Quality Assurance',
    'Hospitality Technology',
  ],
  Transportation: [
    'Logistics',
    'Fleet Management',
    'Dispatch',
    'Route Planning',
    'DOT Regulations',
    'Supply Chain Management',
    "CDL (Commercial Driver's License)",
    'Freight',
    'Cargo',
    'Transportation Safety',
    'GPS Navigation',
    'Scheduling',
    'Cost Reduction',
    'Transportation Planning',
    'Warehousing',
    'Cross-docking',
    'Compliance',
    'Shipping',
    'Receiving',
    'Inventory Management',
    'Vehicle Maintenance',
    '3PL (Third-party Logistics)',
    'Load Balancing',
    'Rail Operations',
    'Air Freight',
    'Sea Freight',
    'Customs Brokerage',
    'LTL (Less Than Truckload)',
    'FTL (Full Truckload)',
    'Distribution Center',
  ],
  Utilities: [
    'Energy Distribution',
    'Water Treatment',
    'Compliance Regulations',
    'Pipeline Management',
    'Renewable Energy',
    'Power Generation',
    'Electrical Grid',
    'Waste Management',
    'SCADA Systems',
    'Infrastructure Maintenance',
    'Smart Grid Technology',
    'Utility Operations',
    'Resource Management',
    'Environmental Policy',
    'Sustainability Initiatives',
    'Power Plant Operations',
    'Natural Gas',
    'Project Management',
    'Efficiency Optimization',
    'Outage Management',
    'Regulatory Affairs',
    'Meter Reading',
    'Energy Audits',
    'Health and Safety',
    'Asset Management',
    'Utility Networks',
    'Customer Service',
    'Technical Support',
    'Emergency Response',
    'GIS Mapping',
  ],
};

export default industry;
