version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      backend-prod:
        condition: service_healthy
      frontend-prod:
        condition: service_started
    networks:
      - shared-network

  backend-prod:
    container_name: ta-backend
    image: ta-backend-prod:1.0.0
    build:
      context: backend
      target: production
      dockerfile: Dockerfile
    command: sh -c 'yarn start:prod'
    networks:
      - shared-network
    ports:
      - 4000:4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://backend-prod:4000"]
      interval: 5s
      timeout: 3s
      retries: 6

  frontend-prod:
    container_name: ta-frontend
    image: ta-frontend-prod:1.0.0
    build:
      context: frontend
      target: production
      dockerfile: Dockerfile
    command: yarn run start:prod
    ports:
      - 3000:3000
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:

volumes:
  db-config:
  db-data:
